# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogforaddnewface.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogForAddNewFace(object):
    def setupUi(self, DialogForAddNewFace):
        DialogForAddNewFace.setObjectName("DialogForAddNewFace")
        DialogForAddNewFace.resize(692, 477)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogForAddNewFace)
        self.buttonBox.setGeometry(QtCore.QRect(190, 360, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(DialogForAddNewFace)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 231, 291))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.selectedPicShow = QtWidgets.QLabel(self.groupBox)
        self.selectedPicShow.setGeometry(QtCore.QRect(20, 30, 191, 191))
        self.selectedPicShow.setObjectName("selectedPicShow")
        self.selectNewFaceBtn = QtWidgets.QPushButton(self.groupBox)
        self.selectNewFaceBtn.setGeometry(QtCore.QRect(60, 260, 80, 26))
        self.selectNewFaceBtn.setObjectName("selectNewFaceBtn")
        self.groupBox_2 = QtWidgets.QGroupBox(DialogForAddNewFace)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 50, 411, 291))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.splitter_3 = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter_3.setGeometry(QtCore.QRect(40, 50, 321, 221))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.nameEdit = QtWidgets.QLineEdit(self.splitter)
        self.nameEdit.setAcceptDrops(True)
        self.nameEdit.setDragEnabled(False)
        self.nameEdit.setObjectName("nameEdit")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.femaleRadio = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.femaleRadio.sizePolicy().hasHeightForWidth())
        self.femaleRadio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.femaleRadio.setFont(font)
        self.femaleRadio.setObjectName("femaleRadio")
        self.horizontalLayout.addWidget(self.femaleRadio)
        self.maleRadio = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.maleRadio.setFont(font)
        self.maleRadio.setObjectName("maleRadio")
        self.horizontalLayout.addWidget(self.maleRadio)
        self.ageEdit = QtWidgets.QLineEdit(self.splitter)
        self.ageEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.ageEdit.setAcceptDrops(True)
        self.ageEdit.setText("")
        self.ageEdit.setMaxLength(100)
        self.ageEdit.setObjectName("ageEdit")
        self.phoneEdit = QtWidgets.QLineEdit(self.splitter)
        self.phoneEdit.setAcceptDrops(True)
        self.phoneEdit.setObjectName("phoneEdit")
        self.emailEdit = QtWidgets.QLineEdit(self.splitter)
        self.emailEdit.setAcceptDrops(True)
        self.emailEdit.setObjectName("emailEdit")

        self.retranslateUi(DialogForAddNewFace)
        self.buttonBox.accepted.connect(DialogForAddNewFace.accept)
        self.buttonBox.rejected.connect(DialogForAddNewFace.reject)
        self.buttonBox.clicked['QAbstractButton*'].connect(DialogForAddNewFace.buttonBox_clicked)
        QtCore.QMetaObject.connectSlotsByName(DialogForAddNewFace)

    def retranslateUi(self, DialogForAddNewFace):
        _translate = QtCore.QCoreApplication.translate
        DialogForAddNewFace.setWindowTitle(_translate("DialogForAddNewFace", "Dialog"))
        self.selectedPicShow.setText(_translate("DialogForAddNewFace", "TextLabel"))
        self.selectNewFaceBtn.setText(_translate("DialogForAddNewFace", "Select..."))
        self.label.setText(_translate("DialogForAddNewFace", "Name:"))
        self.label_2.setText(_translate("DialogForAddNewFace", "Sex:"))
        self.label_3.setText(_translate("DialogForAddNewFace", "Age:"))
        self.label_4.setText(_translate("DialogForAddNewFace", "Phone:"))
        self.label_5.setText(_translate("DialogForAddNewFace", "E-mail:"))
        self.femaleRadio.setText(_translate("DialogForAddNewFace", "Female"))
        self.maleRadio.setText(_translate("DialogForAddNewFace", "Male"))
