# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1204, 665)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 581, 521))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 460, 292, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectBtn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC")
        font.setPointSize(14)
        self.selectBtn.setFont(font)
        self.selectBtn.setObjectName("selectBtn")
        self.horizontalLayout.addWidget(self.selectBtn)
        self.matchBtn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC")
        font.setPointSize(14)
        self.matchBtn.setFont(font)
        self.matchBtn.setObjectName("matchBtn")
        self.horizontalLayout.addWidget(self.matchBtn)
        self.selectedPic = QtWidgets.QLabel(self.groupBox)
        self.selectedPic.setGeometry(QtCore.QRect(40, 60, 480, 320))
        self.selectedPic.setObjectName("selectedPic")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(650, 40, 521, 501))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.matched_pic1 = QtWidgets.QLabel(self.tab1)
        self.matched_pic1.setGeometry(QtCore.QRect(10, 10, 501, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matched_pic1.sizePolicy().hasHeightForWidth())
        self.matched_pic1.setSizePolicy(sizePolicy)
        self.matched_pic1.setObjectName("matched_pic1")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.matched_pic2 = QtWidgets.QLabel(self.tab2)
        self.matched_pic2.setGeometry(QtCore.QRect(10, 10, 501, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matched_pic2.sizePolicy().hasHeightForWidth())
        self.matched_pic2.setSizePolicy(sizePolicy)
        self.matched_pic2.setObjectName("matched_pic2")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.matched_pic3 = QtWidgets.QLabel(self.tab3)
        self.matched_pic3.setGeometry(QtCore.QRect(10, 10, 501, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matched_pic3.sizePolicy().hasHeightForWidth())
        self.matched_pic3.setSizePolicy(sizePolicy)
        self.matched_pic3.setObjectName("matched_pic3")
        self.tabWidget.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.matched_pic4 = QtWidgets.QLabel(self.tab4)
        self.matched_pic4.setGeometry(QtCore.QRect(10, 10, 501, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matched_pic4.sizePolicy().hasHeightForWidth())
        self.matched_pic4.setSizePolicy(sizePolicy)
        self.matched_pic4.setObjectName("matched_pic4")
        self.tabWidget.addTab(self.tab4, "")
        self.tab5 = QtWidgets.QWidget()
        self.tab5.setObjectName("tab5")
        self.matched_pic5 = QtWidgets.QLabel(self.tab5)
        self.matched_pic5.setGeometry(QtCore.QRect(10, 10, 501, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matched_pic5.sizePolicy().hasHeightForWidth())
        self.matched_pic5.setSizePolicy(sizePolicy)
        self.matched_pic5.setObjectName("matched_pic5")
        self.tabWidget.addTab(self.tab5, "")
        self.addBtnTest = QtWidgets.QPushButton(self.centralWidget)
        self.addBtnTest.setGeometry(QtCore.QRect(340, 550, 142, 37))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC")
        font.setPointSize(14)
        self.addBtnTest.setFont(font)
        self.addBtnTest.setObjectName("addBtnTest")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1204, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionSearch_Face = QtWidgets.QAction(MainWindow)
        self.actionSearch_Face.setObjectName("actionSearch_Face")
        self.actionAdd_Face = QtWidgets.QAction(MainWindow)
        self.actionAdd_Face.setObjectName("actionAdd_Face")
        self.menuFile.addAction(self.actionSearch_Face)
        self.menuFile.addAction(self.actionAdd_Face)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.selectBtn.setText(_translate("MainWindow", "选择图片..."))
        self.matchBtn.setText(_translate("MainWindow", "匹配"))
        self.selectedPic.setText(_translate("MainWindow", "TextLabel"))
        self.matched_pic1.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "No.1"))
        self.matched_pic2.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "No.2"))
        self.matched_pic3.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "No.3"))
        self.matched_pic4.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("MainWindow", "No.4"))
        self.matched_pic5.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab5), _translate("MainWindow", "No.5"))
        self.addBtnTest.setText(_translate("MainWindow", "add test"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSearch_Face.setText(_translate("MainWindow", "Search Face"))
        self.actionAdd_Face.setText(_translate("MainWindow", "Add Face"))
