# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 657)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 581, 521))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 450, 292, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectBtn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC")
        font.setPointSize(14)
        self.selectBtn.setFont(font)
        self.selectBtn.setObjectName("selectBtn")
        self.horizontalLayout.addWidget(self.selectBtn)
        self.matchBtn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC")
        font.setPointSize(14)
        self.matchBtn.setFont(font)
        self.matchBtn.setObjectName("matchBtn")
        self.horizontalLayout.addWidget(self.matchBtn)
        self.selectedPic = QtWidgets.QLabel(self.groupBox)
        self.selectedPic.setGeometry(QtCore.QRect(40, 60, 480, 320))
        self.selectedPic.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.selectedPic.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.selectedPic.setFrameShadow(QtWidgets.QFrame.Plain)
        self.selectedPic.setText("")
        self.selectedPic.setObjectName("selectedPic")
        self.addBtnTest = QtWidgets.QPushButton(self.centralWidget)
        self.addBtnTest.setGeometry(QtCore.QRect(40, 550, 142, 37))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC")
        font.setPointSize(14)
        self.addBtnTest.setFont(font)
        self.addBtnTest.setObjectName("addBtnTest")
        self.resultGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.resultGroupBox.setGeometry(QtCore.QRect(630, 20, 551, 521))
        self.resultGroupBox.setFlat(False)
        self.resultGroupBox.setObjectName("resultGroupBox")
        self.splitter = QtWidgets.QSplitter(self.resultGroupBox)
        self.splitter.setGeometry(QtCore.QRect(10, 30, 400, 31))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.firstBtn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.firstBtn.setFont(font)
        self.firstBtn.setObjectName("firstBtn")
        self.secondBtn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.secondBtn.setFont(font)
        self.secondBtn.setObjectName("secondBtn")
        self.thirdBtn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.thirdBtn.setFont(font)
        self.thirdBtn.setObjectName("thirdBtn")
        self.fourthBtn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fourthBtn.setFont(font)
        self.fourthBtn.setObjectName("fourthBtn")
        self.fifthBtn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fifthBtn.setFont(font)
        self.fifthBtn.setObjectName("fifthBtn")
        self.matchedPicShow = QtWidgets.QLabel(self.resultGroupBox)
        self.matchedPicShow.setGeometry(QtCore.QRect(10, 90, 251, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matchedPicShow.sizePolicy().hasHeightForWidth())
        self.matchedPicShow.setSizePolicy(sizePolicy)
        self.matchedPicShow.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.matchedPicShow.setText("")
        self.matchedPicShow.setObjectName("matchedPicShow")
        self.layoutWidget1 = QtWidgets.QWidget(self.resultGroupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(271, 91, 241, 231))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.nameShow = QtWidgets.QLineEdit(self.layoutWidget1)
        self.nameShow.setReadOnly(True)
        self.nameShow.setObjectName("nameShow")
        self.horizontalLayout_2.addWidget(self.nameShow)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.sexShow = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sexShow.setReadOnly(True)
        self.sexShow.setObjectName("sexShow")
        self.horizontalLayout_6.addWidget(self.sexShow)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.ageShow = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ageShow.setReadOnly(True)
        self.ageShow.setObjectName("ageShow")
        self.horizontalLayout_3.addWidget(self.ageShow)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.phoneShow = QtWidgets.QLineEdit(self.layoutWidget1)
        self.phoneShow.setReadOnly(True)
        self.phoneShow.setObjectName("phoneShow")
        self.horizontalLayout_4.addWidget(self.phoneShow)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.emailShow = QtWidgets.QLineEdit(self.layoutWidget1)
        self.emailShow.setReadOnly(True)
        self.emailShow.setObjectName("emailShow")
        self.horizontalLayout_5.addWidget(self.emailShow)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionSearch_Face = QtWidgets.QAction(MainWindow)
        self.actionSearch_Face.setObjectName("actionSearch_Face")
        self.actionAdd_Face = QtWidgets.QAction(MainWindow)
        self.actionAdd_Face.setObjectName("actionAdd_Face")
        self.menuFile.addAction(self.actionSearch_Face)
        self.menuFile.addAction(self.actionAdd_Face)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectBtn.setText(_translate("MainWindow", "选择图片..."))
        self.matchBtn.setText(_translate("MainWindow", "匹配"))
        self.addBtnTest.setText(_translate("MainWindow", "添加新人脸"))
        self.resultGroupBox.setTitle(_translate("MainWindow", "匹配结果"))
        self.firstBtn.setText(_translate("MainWindow", "No.1"))
        self.secondBtn.setText(_translate("MainWindow", "No.2"))
        self.thirdBtn.setText(_translate("MainWindow", "No.3"))
        self.fourthBtn.setText(_translate("MainWindow", "No.4"))
        self.fifthBtn.setText(_translate("MainWindow", "No.5"))
        self.label.setText(_translate("MainWindow", "姓名"))
        self.label_5.setText(_translate("MainWindow", "性别"))
        self.label_2.setText(_translate("MainWindow", "年龄"))
        self.label_3.setText(_translate("MainWindow", "手机"))
        self.label_4.setText(_translate("MainWindow", "邮箱"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSearch_Face.setText(_translate("MainWindow", "Search Face"))
        self.actionAdd_Face.setText(_translate("MainWindow", "Add Face"))
